server :
   port : 8081
spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 753653563470-u274dup0as9dekh3k03jkphlgr9husmu.apps.googleusercontent.com
            client-secret: bzfI26id4zk4s5s3Q4btzuRj
          facebook:
            client-id: 819138195121444
            client-secret: 12ef78c23201196f2f165e203c4e2579
custom:
  oauth2:
    kakao:
      client-id: da7f0333464823618b75fa11dadde196