/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Spring.Boot.Community.Web;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
